### ISSUE TITLE
Mime dependency is broken

### ISSUE THREAD

**Issue by booleanbetrayal** [bezoerb/asset-resolver#212]
During the last `asset-resolver` dependency update pass, the Mime module was updated to 2.0.3 in which its `index.js` file attempts to `require('./Mime')`. This was prior to a follow-up commit in that project that renamed its `mime.js` file to `Mime.js`. Unfortunately, that means that the current `asset-resolver` Mime dependency is throwing the following:

```
Error: Cannot find module './Mime'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/some_project/node_modules/asset-resolver/node_modules/mime/index.js:3:14)
```

Should be fixed with an update to a more recent version.

**Comment by bezoerb** [comment]
Thanks @booleanbetrayal. Is fixed [v1.0.3](https://github.com/bezoerb/asset-resolver/releases/tag/v1.0.3)
